name: CICD
run-name: Running
on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AWS_REGION: ap-northeast-2
  AWS_S3_BUCKET: s3bucketjisupark
  AWS_CODE_DEPLOY_APPLICATION: cicd-CD
  AWS_CODE_DEPLOY_GROUP: cicd-CD-group
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

jobs:
  build-with-gradle:
    runs-on: ubuntu-latest
    steps:
      - name: master 브랜치로 이동
        uses: actions/checkout@v3
        with:
          ref: master

      - name: JDK 17 설치
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: gradlew에 실행 권한 부여
        run: chmod +x ./gradlew

      - name: 프로젝트 빌드
        run: ./gradlew clean build -x test

      - name: AWS credential 설정
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.CICD_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.CICD_SECRET_KEY }}

      - name: S3에 업로드
        run: aws deploy push --application-name cicd-CD --ignore-hidden-files --s3-location s3://s3bucketjisupark/cicd/$GITHUB_SHA.zip --source . --region ap-northeast-2

      - name: EC2에 배포
        run: aws deploy create-deployment --application-name ${{ env.AWS_CODE_DEPLOY_APPLICATION }} --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name ${{ env.AWS_CODE_DEPLOY_GROUP }} --s3-location bucket=$AWS_S3_BUCKET,key=cicd/$GITHUB_SHA.zip,bundleType=zip

      - name: Spring Boot 애플리케이션 실행
        run: |
          export DB_HOST=${{ secrets.DB_HOST }}
          export DB_USERNAME=${{ secrets.DB_USERNAME }}
          export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          
          
          java -Dspring.datasource.url=jdbc:mysql://${DB_HOST}:3306/lostarknoticeboard \
               -Dspring.datasource.username=${DB_USERNAME} \
               -Dspring.datasource.password=${DB_PASSWORD} \
               -Dspring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver \
               -Dspring.jpa.hibernate.ddl-auto=update \
               -Dspring.jpa.show-sql=true \
               -jar build/libs/LostArkNoticeBoard-0.0.1-SNAPSHOT.jar
